runtime! basic.vim
" Some settings should be loaded before plugins loading
" runtime! before.vim

call plug#begin('~/.vim/plugged')
runtime! plugins.vim
call plug#end()

runtime! plugin_settings/*.vim
runtime! colorscheme.vim
