mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: false
bind-address: '*'
mode: rule
log-level: debug
external-controller: '127.0.0.1:9090'
external-ui: "/usr/share/yacd"
dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:1053
    default-nameserver:
        - 1.1.1.1
        - 114.114.114.114
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://dns.cloudflare-dns.com/dns-query', 'tls://1.1.1.1:853', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
