#!/bin/sh

pkill picom
picom --config ~/.config/picom/picom.conf &

xscreensaver --no-splash &
xss-lock --ignore-sleep -- xscreensaver-command -lock &

# PulseAudio system tray
pasystray &

# start network manager
nm-applet &

# enable bluetooth applet
blueman-applet &

fcitx5 &

udiskie --tray &
bing-random-rb &
dunst &
copyq &
