theme = "space-villain"
icons = "awesome"

[[block]]
block = "networkmanager"
device_format = "{icon}{ap}"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
